pkg/cybr/api/safes.go, pkg/cybr/api/safes_test.go
- quick bug fix for url encoding
- Test for create safe
- Test for delete safe
=> Tests for creating and deleting safes

pkg/cybr/api/accounts.go, pkg/cybr/api/accounts_test.go, pkg/cybr/helpers/httpjson/httpjson.go, pkg/cybr/helpers/httpjson/query.go
=> Account actions 

cmd/safes.go, pkg/cybr/api/safes.go, pkg/cybr/api/safes_test.go, pkg/cybr/helpers/httpjson/httpjson.go, pkg/cybr/version.go, release.json
=> Expand safes

cmd/applications.go, pkg/cybr/api/applications.go, pkg/cybr/api/applications_test.go
- Add applications
- Delete application
- Add application authentication method
- Delete application authentication method
=> Expand application api cli

cmd/accounts.go, cmd/applications.go, cmd/safes.go
- Must provide `list` action to list desired resources
=> Do not list unless prompted to list

cmd/applications.go
- renamed `authn-add` -> `add-authn`
- renamed `authn-delete` -> `delete-authn`
- renamed `method list` -> `list-authn`
=> Fix application authn commands

pkg/cybr/api/accounts_test.go, pkg/cybr/api/applications_test.go, pkg/cybr/api/safes.go, pkg/cybr/helpers/httpjson/httpjson.go
- Fix Tests
- Updated httpjson to not decode body if request failed to send
=> Fix unit tests

dev/add-delete-pas-application.sh
Demonstrating how to onboard and application, safe and an account and then deleting all of the resources using bash.
=> Dev creating application flow

pkg/cybr/api/accounts_test.go, pkg/cybr/api/applications_test.go, pkg/cybr/api/client_test.go, pkg/cybr/api/safes_test.go
=> Fix #44 refactor tests v006

cmd/accounts.go, cmd/applications.go, cmd/logoff.go, cmd/root.go, cmd/safes.go, pkg/cybr/api/accounts.go, pkg/cybr/api/applications.go, pkg/cybr/api/auth.go, pkg/cybr/api/client.go, pkg/cybr/api/safes.go, pkg/cybr/api/server.go, pkg/cybr/helpers/httpjson/httpjson.go, pkg/logger/cmd.go, pkg/logger/logger.go
=> Add #37 add verbose v006

cmd/users.go, pkg/cybr/api/users.go, pkg/cybr/api/users_test.go
#30 Unsuspend a user from failed logon attempts
=> #30 Unsuspend a user from failed logon attempts

cmd/conjur.go, pkg/cybr/conjur/client.go, pkg/cybr/conjur/conjurrc.go, pkg/cybr/conjur/logon.go
- added `--self-signed` flag for `cybr conjur logon`
=> Fix 52 conjur logon fail

cmd/logon.go
- `cybr logon --non-interactive` gives the ability to use the environment variable `PAS_PASSWORD` as the password
=> Fix #32 add cybr logon --non-interactive

cmd/accounts.go, pkg/cybr/api/accounts.go, pkg/cybr/api/accounts_test.go
- Added `cybr accounts get-password`
- Added `cybr accounts verify`
- Added `cybr accounts change`
- Added `cybr accounts reconcile`
=> #49 add account actions

pkg/cybr/conjur/client.go
- Use environment variables `CONJUR_ACCOUNT`, `CONJUR_APPLIANCE_URL`, `CONJUR_AUTHN_LOGIN`, `CONJUR_AUTHN_API_KEY` and `CONJUR_CERT_FILE` if found instead of `~/.netrc` and `~/.conjurrc` files.
=> Fix #59 use environment variables for authentication and configuration if present

cmd/ccp.go, pkg/cybr/ccp/ccp.go, pkg/cybr/ccp/ccp_test.go
- Added `cybr ccp get-account` command. Resolves #67
=> Fix #67 ccp retrieve account beta v0.1.1

cmd/logon.go
- Add concurrent sessions to the CLI #88
=> Add concurrent sessions to the CLI #88

pkg/cybr/conjur/conjurrc.go
- Resolves #96 allow more than 2 certificates in cert chain
=> #96 allow more than 2 certificates in cert chain

cmd/conjur.go
- #90 add no limit to default `cybr conjur list` command
=> #90 add no limit to default cybr conjur list command

cmd/accounts.go, pkg/cybr/api/responses/getaccount.go
-  #47 `cybr accounts move` command has been added
=> V0.1.2 beta #47 account move

pkg/cybr/conjur/client.go, pkg/cybr/conjur/conjurrc.go, pkg/cybr/conjur/netrc.go
- Resolves #98 so windows login works correctly
=> Resolves #98 so windows login works correctly

cmd/logon.go
- Add `--password` flag so CCP can retrieve REST API password #66
=> Add --password flag so CCP can retrieve REST API password #66

cmd/cem.go, go.mod, go.sum, pkg/cybr/api/client.go, pkg/cybr/cem/cem.go, pkg/cybr/helpers/util/util.go
=> Adding 6 CEM sub-commands (#105)

Dockerfile
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-DEBIAN11-GLIBC-1296898
- https://snyk.io/vuln/SNYK-DEBIAN11-OPENSSL-1569405
- https://snyk.io/vuln/SNYK-DEBIAN11-OPENSSL-1569405
- https://snyk.io/vuln/SNYK-DEBIAN11-OPENSSL-1569408
- https://snyk.io/vuln/SNYK-DEBIAN11-OPENSSL-1569408
=> fix: Dockerfile to reduce vulnerabilities (#120)

pkg/cybr/conjur/client.go
Fixed #175 by adding a check for .conjurrc file existing prior to attempting environment variable authentication.  This will require that the .conjurrc and .netrc files are not present in order to use environment variables or authenticators.
=> Fixes #175 add check for .conjurrc before env authn

cmd/conjur.go
=> Fixed #185 Add --password/-p to cybr conjur logon

cmd/accounts.go, docs/cybr_accounts_add.md
Secret parameter should be -c, not -s
=> Typo in doc cybr_accounts_add

cmd/accounts.go, pkg/cybr/api/accounts.go, pkg/cybr/api/accounts_test.go
=> Add unlock & checkin to cybr accounts

cmd/accounts.go, cmd/logon.go, pkg/cybr/api/accounts.go, pkg/cybr/api/accounts_test.go, pkg/cybr/api/requests/changeaccountcredential.go
=> Fixes #207 Add remaining scopes to cybr accounts change

cmd/logon.go, pkg/cybr/identity/startauth.go
=> Fixes #209 Add support for PodFqdn for Identity authn
